export const CHANGE_EVENT = 'EJ/CHANGE_EVENT';
export const MESSAGE_CREATE = 'EJ/MESSAGE_CREATE';
export const DIALOG_SHOW = 'EJ/DIALOG_SHOW';
export const DIALOG_HIDE = 'EJ/DIALOG_HIDE';
export const CHANGE_COMPANY_ADMIN = 'EJ/CHANGE_COMPANY_ADMIN';
export const BULK_CHANGE_COMPANY_ADMIN = 'EJ/BULK_CHANGE_COMPANY_ADMIN';
export const CHANGE_RESOURCE_FLAG = 'EJ/CHANGE_RESOURCE_FLAG';
